name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 24 horas
    - cron: "0 */24 * * *"
  
  # Permite rodar a action manualmente na aba "Actions"
  workflow_dispatch:

    # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    # PERMISSÃO NECESSÁRIA: Permite que o bot comite o arquivo gerado
    permissions:
      contents: write

    steps:
      # Gera a animação da cobrinha
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: MachadoCodes
          # Gera a versão normal e a versão Dark Mode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz o push do arquivo para a branch "output"
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
